// frontend/src/components/Tabs.vue
<template>
  <nav class="tabs">
    <div class="tabs-container">
      <button
        v-for="tab in tabs"
        :key="tab.id"
        :class="['tab', { active: activeTab === tab.id }]"
        @click="$emit('tab-change', tab.id)"
      >
        {{ tab.label }}
      </button>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref } from 'vue'

defineProps<{
  activeTab: 'all' | 'leaderboard' | 'success'
}>()

defineEmits<{
  (e: 'tab-change', tab: 'all' | 'leaderboard' | 'success'): void
}>()

const tabs = ref([
  { id: 'all' as const, label: 'All Projects' },
  { id: 'leaderboard' as const, label: 'Leaderboard' },
  { id: 'success' as const, label: 'Success Stories' }
])
</script>

<style scoped>
.tabs {
  padding: 0 2rem;
  background: var(--white);
  border-bottom: 1px solid var(--gray-200);
}

.tabs-container {
  max-width: 1400px;
  margin: 0 auto;
  display: flex;
  gap: 0.5rem;
  padding: 1.5rem 0;
}

.tab {
  background: transparent;
  border: 1px solid var(--gray-200);
  color: var(--gray-600);
  padding: 0.75rem 1.5rem;
  font-size: 0.875rem;
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  cursor: pointer;
  transition: all 0.2s ease;
  font-family: 'Inter', -apple-system, sans-serif;
}

.tab:hover {
  border-color: var(--black);
  color: var(--black);
}

.tab.active {
  background: var(--black);
  color: var(--white);
  border-color: var(--black);
}

@media (max-width: 768px) {
  .tabs {
    padding: 0 1rem;
  }
  
  .tabs-container {
    gap: 0.25rem;
    padding: 1rem 0;
  }
  
  .tab {
    padding: 0.5rem 1rem;
    font-size: 0.75rem;
    flex: 1;
  }
}
</style>

// frontend/src/components/Tabs.tsx
import { motion } from 'framer-motion'
import { cn } from '@/lib/utils'

interface TabsProps {
  activeTab: 'all' | 'leaderboard' | 'success'
  onTabChange: (tab: 'all' | 'leaderboard' | 'success') => void
}

export function Tabs({ activeTab, onTabChange }: TabsProps) {
  const tabs = [
    { id: 'all' as const, label: 'All Projects' },
    { id: 'leaderboard' as const, label: 'Leaderboard' },
    { id: 'success' as const, label: 'Success Stories' },
  ]

  return (
    <nav className="py-4 px-4 bg-black border-b border-white/10">
      <div className="container mx-auto max-w-7xl">
        <div className="flex gap-2 justify-center">
          {tabs.map((tab) => (
            <motion.button
              key={tab.id}
              onClick={() => onTabChange(tab.id)}
              className={cn(
                "px-6 py-3 rounded-2xl font-medium text-sm transition-all",
                "border backdrop-blur-sm",
                activeTab === tab.id
                  ? "bg-white/10 border-white/20 text-white shadow-lg"
                  : "bg-white/5 border-white/10 text-white/60 hover:bg-white/10 hover:text-white/80"
              )}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            >
              {tab.label}
            </motion.button>
          ))}
        </div>
      </div>
    </nav>
  )
}
