// frontend/src/App-react.tsx
import { useState, useEffect } from 'react'
import { Header as HeroHeader, HeroContent, PulsingCircle, ShaderBackground } from "@/components/ui/shaders-hero-section"
import HeroSection02 from "@/components/ui/ruixen-hero-section-02"
import { Stats } from './components/Stats'
import { Tabs } from './components/Tabs'
import { ProjectGrid } from './components/ProjectGrid'
import { ProjectPage } from './components/ProjectPage'
import { MatchProjectsPage } from './components/MatchProjectsPage'
import { ProjectsPage } from './components/ProjectsPage'
import { fetchProjects, fetchLeaderboard, fetchSuccessStories, fetchStats, fetchProject } from './services/api'
import type { Project, Stats as StatsType } from './types'

export default function App() {
  const [activeTab, setActiveTab] = useState<'all' | 'leaderboard' | 'success'>('all')
  const [projects, setProjects] = useState<Project[]>([])
  const [leaderboard, setLeaderboard] = useState<Project[]>([])
  const [successStories, setSuccessStories] = useState<Project[]>([])
  const [stats, setStats] = useState<StatsType | null>(null)
  const [loading, setLoading] = useState(true)
  const [selectedProjectId, setSelectedProjectId] = useState<string | null>(null)
  const [selectedProject, setSelectedProject] = useState<Project | null>(null)
  const [isProjectPageOpen, setIsProjectPageOpen] = useState(false)
  const [isMatchPageOpen, setIsMatchPageOpen] = useState(false)
  const [isProjectsPageOpen, setIsProjectsPageOpen] = useState(false)
  const [preSelectedProject, setPreSelectedProject] = useState<Project | null>(null)

  // Load data when component mounts
  useEffect(() => {
    loadData()
  }, [])

  const loadData = async () => {
    setLoading(true)
    try {
      const [projectsData, leaderboardData, successData, statsData] = await Promise.all([
        fetchProjects(),
        fetchLeaderboard(),
        fetchSuccessStories(),
        fetchStats()
      ])
      
      setProjects(projectsData)
      setLeaderboard(leaderboardData)
      setSuccessStories(successData)
      setStats(statsData)
    } catch (error) {
      console.error('Error loading data:', error)
    } finally {
      setLoading(false)
    }
  }

  const displayProjects = activeTab === 'leaderboard' 
    ? leaderboard 
    : activeTab === 'success' 
    ? successStories 
    : projects

  // Load project when project page opens
  useEffect(() => {
    if (selectedProjectId && isProjectPageOpen) {
      fetchProject(selectedProjectId)
        .then(project => {
          setSelectedProject(project)
        })
        .catch(error => {
          console.error('Error loading project:', error)
        })
    }
  }, [selectedProjectId, isProjectPageOpen])

  // Show project page or match page or projects page or main page
  if (isProjectPageOpen && selectedProject) {
    return (
      <ProjectPage
        project={selectedProject}
        onClose={() => {
          setIsProjectPageOpen(false)
          setSelectedProjectId(null)
          setSelectedProject(null)
        }}
      />
    )
  }

  if (isMatchPageOpen) {
    return (
      <MatchProjectsPage
        onClose={() => {
          setIsMatchPageOpen(false)
          setPreSelectedProject(null)
        }}
        preSelectedProject={preSelectedProject}
      />
    )
  }

  if (isProjectsPageOpen) {
    return (
      <ProjectsPage
        onClose={() => {
          setIsProjectsPageOpen(false)
        }}
      />
    )
  }

  return (
    <div className="min-h-screen bg-black">
      {/* Main Hero Section with Shader Background - Fullscreen */}
      <ShaderBackground>
        <HeroHeader />
        <HeroContent 
          onViewProjects={() => setIsProjectsPageOpen(true)}
          onMatchProjects={() => {
            setIsMatchPageOpen(true)
          }}
        />
        <PulsingCircle />
      </ShaderBackground>
    </div>
  )
}

// frontend/src/App.vue
<template>
  <div class="app">
    <Header />
    <Stats :stats="stats" v-if="stats" />
    <Tabs :active-tab="activeTab" @tab-change="handleTabChange" />
    <ProjectGrid 
      :projects="displayProjects" 
      :loading="loading"
      @refresh="loadData"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import Header from './components/Header.vue'
import Stats from './components/Stats.vue'
import Tabs from './components/Tabs.vue'
import ProjectGrid from './components/ProjectGrid.vue'
import { fetchProjects, fetchLeaderboard, fetchSuccessStories, fetchStats } from './services/api'
import type { Project, Stats as StatsType } from './types'

const activeTab = ref<'all' | 'leaderboard' | 'success'>('all')
const projects = ref<Project[]>([])
const leaderboard = ref<Project[]>([])
const successStories = ref<Project[]>([])
const stats = ref<StatsType | null>(null)
const loading = ref(true)

const displayProjects = computed(() => {
  if (activeTab.value === 'leaderboard') return leaderboard.value
  if (activeTab.value === 'success') return successStories.value
  return projects.value
})

const handleTabChange = (tab: 'all' | 'leaderboard' | 'success') => {
  activeTab.value = tab
}

const loadData = async () => {
  loading.value = true
  try {
    const [projectsData, leaderboardData, successData, statsData] = await Promise.all([
      fetchProjects(),
      fetchLeaderboard(),
      fetchSuccessStories(),
      fetchStats()
    ])
    
    projects.value = projectsData
    leaderboard.value = leaderboardData
    successStories.value = successData
    stats.value = statsData
  } catch (error) {
    console.error('Error loading data:', error)
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadData()
})
</script>

<style scoped>
.app {
  min-height: 100vh;
  background: var(--white);
}
</style>
